apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster-deployment
  labels:
    app: hamster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hamster
  template:
    metadata:
      labels:
        app: hamster
    spec:
      containers:
      - name: hamster
        # This image performs intense math calculations to consume CPU
        image: vsphere-docker-virtual.packages.vcfd.broadcom.net/photon:1.0
        resources:
          requests:
            cpu: 100m    # Intentionally low request
            memory: 50Mi
        command: ["/bin/sh"]
        args:
          - "-c"
          - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"