apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hamster-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hamster-deployment
  updatePolicy:
    updateMode: "Off"   # "Off" calculates recommendations but won't restart pods. 
                        # Change to "Auto" to let VPA actually restart/resize them.