{
 "title": "application-qps-2min",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"kubernetes-pods\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": " (node_memory_MemTotal_bytes{job=\"kubernetes-pods\"} - node_memory_MemAvailable_bytes{job=\"kubernetes-pods\"}) / node_memory_MemTotal_bytes{job=\"kubernetes-pods\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}